# Generated by Django 3.1.6 on 2021-08-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_bookde'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookde',
            new_name='Booked',
        ),
    ]
