# Generated by Django 3.1.6 on 2021-08-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20210827_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20, null=True)),
                ('c_email', models.CharField(max_length=20, null=True)),
                ('c_mobile', models.CharField(max_length=20, null=True)),
                ('c_purpose', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
