# Generated by Django 4.0.1 on 2022-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='activity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='history',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
