# Generated by Django 4.0.1 on 2022-04-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_room_activity_room_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='p_city',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_no',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='p_state',
        ),
        migrations.AddField(
            model_name='room',
            name='t_price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
